Script Update

diff --git a/modules/main b/modules/main
--- a/modules/main
+++ b/modules/main
@@ -1,19 +1,15 @@
 #!/bin/bash
 
 # Parse arguments before checking the value of LOCAL
-while [ $# -gt 0 ]; do
-  case "$1" in
-      --local)
-          LOCAL="YES"
-          shift 1 # Only shift 1 argument here since --local has no extra argument
-          continue
-          ;;
-      *)
-          echo -e "${LB}${RED} [E] Invalid Argument"
-          exit 1
-          ;;
-  esac
-done
+# while [ $# -gt 0 ]; do
+#   case "$1" in
+#       --local)
+#           LOCAL="YES"
+#           shift 1 # Only shift 1 argument here since --local has no extra argument
+#           continue
+#           ;;
+#   esac
+# done
 
 # Now check the value of LOCAL
 if [[ "$LOCAL" == "YES" ]]; then
@@ -49,4 +45,173 @@ source $MODHEL/info_cpu
 source $MODHEL/info_kernel
 source $MODHEL/info_battery
 
-source $HELPER/args
+MAN="$HELPER/man"
+
+# First check if --save is the only argument
+if [[ "$#" -eq 1 && "$1" == "--save" ]]; then
+    # Set SOUT to enable saving
+    SOUT="| tee /dev/tty | sed 's/\x1b\[[0-9;]*m//g' >> $LOGFILE"
+    
+    # Run default functions (distro_info and system_info_hostnamectl)
+    # RUNwoh "general_system_info"
+    # RUNwoh "distro_info"
+    RUNwoh "system_info"
+
+# Otherwise, handle other cases (including --save combined with other arguments)
+else
+    for arg in "$@"; do
+        if [[ "$arg" == "--pretty" ]]; then
+            PRETTYP="true"
+        elif [[ "$arg" == "--save" ]]; then
+            SOUT="| tee /dev/tty | sed 's/\x1b\[[0-9;]*m//g' >> $LOGFILE"
+            break
+        fi
+    done
+fi
+
+# Check if no arguments are provided
+if [[ $# -eq 0 ]]; then
+    # RUNwoh "general_system_info"
+    # RUNwoh "distro_info"
+    RUNwoh "system_info"
+fi
+
+# Argument handling ${BLUE}(Updated to handle multiple arguments)
+while [[ $# -gt 0 ]]; do
+    key="$1"
+    case $key in
+        -net) # EXTERNAL CUSTOM SCRIPT
+            python $MODCOR/sys_net.py
+            
+            ;;        
+        -v)
+            VLEVEL="$2"
+            if [[ "$VLEVEL" =~ ^[1-8]$ ]]; then
+                VLEVEL="-v $2"
+                RUNwoh "complete_system_info"
+            else
+                echo -e "${LB}${RED}[E]${RT} The verbosity value must be between 1 and 8. Running default (1)."
+                VLEVEL="-v 1"
+                RUNwoh "complete_system_info"
+            fi
+            shift # past argument
+            shift # past value
+            ;;
+        --local)
+            INSTALLDIR="."
+            shift
+            ;;
+
+        -cpu)
+            RUNwoh "cpu_info"
+            shift
+            ;;
+        -mem)
+            RUNwoh "memory_info"
+            RUNwoh "detailed_memory_info"
+            shift
+            ;;
+        -disks)
+            RUNwoh "disk_storage_info"
+            shift
+            ;;
+        -devices)
+            RUNwoh "pci_devices"
+            RUNwoh "usb_devices"
+            shift
+            ;;
+        -networks)
+            RUNwoh "network_info"
+            RUNwoh "network_connections"
+            shift
+            ;;
+        -kernel)
+            RUNwoh "kernel_boot_params"
+            RUNwoh "kernel_modules"
+            shift
+            ;;
+        -gpu)
+            RUNwoh "graphics_info"
+            shift
+            ;;
+        -battery)
+            RUNwoh "battery_info"
+            shift
+            ;;
+        -pkgs)
+            RUNwoh "installed_packages"
+            shift
+            ;;
+        -distro)
+            RUNwoh "distro_info"
+            shift
+            ;;
+        --all-short|-all)
+            #RUNwoh "general_system_info" 
+            #RUNwoh "distro_info" 
+            #RUNwoh "system_info_hostnamectl"
+            RUNwoh "system_info"
+            RUNwoh "complete_system_info"
+            RUNwoh "kernel_boot_params" 
+            RUNwoh "kernel_modules" 
+            RUNwoh "battery_info" 
+            RUNwoh "cpu_info" 
+            RUNwoh "graphics_info" 
+            RUNwoh "memory_info" 
+            RUNwoh "detailed_memory_info" 
+            RUNwoh "disk_storage_info" 
+            RUNwoh "pci_devices" 
+            RUNwoh "usb_devices" 
+            RUNwoh "network_info" 
+            RUNwoh "network_connections" 
+            RUNwoh "installed_packages" 
+            shift
+            ;;
+        --all-detailed|-ald)
+            # RUNwoh "distro_info" 
+            # RUNwoh "system_info_hostnamectl"
+            # RUNwoh "general_system_info"
+            RUNwoh "system_info"
+            RUNwoh "complete_system_info"
+            RUNwoh "kernel_boot_params"
+            RUNwoh "kernel_modules"
+            RUNwoh "battery_info"
+            RUNwoh "cpu_info"
+            RUNwoh "graphics_info"
+            RUNwoh "memory_info"
+            RUNwoh "detailed_memory_info"
+            RUNwoh "disk_storage_info"
+            RUNwoh "pci_devices"
+            RUNwoh "usb_devices"
+            RUNwoh "network_info"
+            RUNwoh "network_connections"
+            RUNwoh "installed_packages"
+            
+            shift
+            ;;
+        -check)
+            RUNwoh "system_recommended"
+            exit 0
+            ;;
+        --pretty)
+            shift
+            ;;
+        --save)
+            savelog
+            shift
+            ;;
+        --help|-h|-H)
+            echo -e "$MAN"
+            exit 0
+            ;;
+        *)
+            echo -e "${LB}${RED}[E]${RT} One or more arguments are invalid. Use $0 --help to see all available commands."
+            exit 1
+            ;;
+    esac
+done
+
+# Output result based on whether --save was used
+if [[ -n "$SOUT" ]]; then
+    echo -e "${LB}${GREEN}[✔] System information gathered successfully. Check $LOGFILE for details.${RT}"
+fi
