Stable

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -1,10 +1,9 @@
 #!/bin/bash
 
-RT='\033[0m'
-LB='\n'
-GREEN="\033[0;32m"
-RED="\033[0;31m"
-CYAN="\033[0;36m"
+# SysNet/Sonda installation script
+# Created by @yonasuriv
+
+source lib/includes/colors
 
 # Define variables
 REPO_URL="https://github.com/yonasuriv/sonda"
@@ -12,9 +11,7 @@ SHARED_DIR="/usr/share/sonda"
 BIN_DIR="/usr/bin"
 BIN_NAME="sonda"
 BIN_LOCALNAME="init"
-BIN_LOCALPATH="$SHARED_DIR/modules/core/$BIN_LOCALNAME"
-
-TEMP_DIR=$(mktemp -d)
+BIN_LOCALPATH="$SHARED_DIR/bin/$BIN_LOCALNAME"
 
 # Ensure the script is run with sudo/root permissions
 if sudo -n true 2>/dev/null; then
@@ -23,41 +20,14 @@ else
     echo -ne "${LB}${RED}[E]${RT} This script must be run as root. Please enter your "; sudo -v || { echo -e "${RED}[E]${RT} Operation cancelled."; exit 1; }
 fi
 
-# # Step 1: Download the repository
-# echo -e "${LB}${CYAN}   ${RT} Cloning the repository from $REPO_URL into $TEMP_DIR..."
-# git clone $REPO_URL $TEMP_DIR 2>/dev/null || { echo -e "${RED}[E]${RT} Failed to clone repository."; exit 1; }
-
-# # Step 2: Create the shared directory if it doesn't exist
-# if [ ! -d "$SHARED_DIR" ]; then
-#   echo -e "${CYAN}   ${RT} Creating shared directory at $SHARED_DIR..."
-#   sudo mkdir -p $SHARED_DIR || { echo -e "${RED}[E]${RT} Failed to create directory."; exit 1; }
-# fi
-
-# # Step 3: Copy the repository files to the shared directory
-# echo -e "${CYAN}   ${RT} Copying repository to $SHARED_DIR..."
-# sudo cp -r $TEMP_DIR/* $SHARED_DIR || { echo -e "${RED}[E]${RT} Failed to copy files to $SHARED_DIR."; exit 1; }
-
 sudo mkdir -p $SHARED_DIR
-sudo cp -rf "$(pwd)/." "$SHARED_DIR"
+sudo cp -rf "$(pwd)"/* "$SHARED_DIR"
+sudo cp -r $BIN_LOCALPATH $BIN_DIR/$BIN_NAME || { echo -e "${RED}[E]${RT} Failed to copy binary to /usr/bin."; exit 1; }
+sudo cp -f static/shortcuts/sonda.desktop /usr/share/applications/sonda.desktop
 
-# Step 4: Check if the binary exists in modules/$BIN_LOCALNAME
-if [ ! -f "$BIN_LOCALPATH" ]; then
-  echo -e "${RED}[E]${RT} The $BIN_LOCALNAME binary was not found in $SHARED_DIR/modules. Please ensure it is built correctly."
-  exit 1
-fi
-
-# Step 5: Move the binary to /usr/bin and rename to sonda
-echo -e "${CYAN}   ${RT} Installing binary as $BIN_NAME to $BIN_DIR..."
-sudo cp $BIN_LOCALPATH $BIN_DIR/$BIN_NAME || { echo -e "${RED}[E]${RT} Failed to copy binary to /usr/bin."; exit 1; }
+sudo chmod 644 /usr/share/sonda/static/icons/sonda.png
 sudo chmod +x $BIN_DIR/$BIN_NAME
 
-sudo sudo cp -Rf static/shortcuts/sonda.desktop /usr/share/applications/sonda.desktop
-
-# # Step 6: Clean up
-# echo -e "${CYAN}   ${RT} Cleaning up temporary files..."
-# rm -rf $TEMP_DIR
-
-# Step 7. Install dependencies
 sudo apt install -y lolcat inxi > /dev/null 2>&1
 
 echo -e "${LB}${GREEN} ✔ ${RT} Installation completed. You can now run 'sonda' from the terminal."
